Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ax = df_res_1.head(0).plot(subplots=True,    #1
                           layout=(2,2),     #2
                           figsize=(8,5))    #3          
                                             #4
ax[0,0].plot('インフレ率', data=df_res_1, linewidth=4)
ax[0,0].plot('インフレ率', data=df_res_2, linewidth=4, linestyle=':')
ax[0,0].set_title('インフレ率',size=20)
                                             #5
ax[0,1].plot('産出量', data=df_res_1, linewidth=4)
ax[0,1].plot('産出量', data=df_res_2, linewidth=4, linestyle=':')
ax[0,1].set_title('産出量',size=20)
                                             #6
ax[1,0].plot('名目利子率', data=df_res_1, linewidth=4)
ax[1,0].plot('名目利子率', data=df_res_2, linewidth=4, linestyle=':')
ax[1,0].set_title('名目利子率',size=20)
                                             #7
ax[1,1].plot('実質利子率', data=df_res_1, linewidth=4)
ax[1,1].plot('実質利子率', data=df_res_2, linewidth=4, linestyle=':')
ax[1,1].set_title('実質利子率',size=20)

fig.legend(['ケース１','ケース２'],             #8
           fontsize=13,                      #9
           ncol=2,                           #10
           loc=7)
#            bbox_to_anchor=(0.7, 1.1))        # 11
pass
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[15], line 21[0m
[1;32m     18[0m ax[[38;5;241m1[39m,[38;5;241m1[39m][38;5;241m.[39mplot([38;5;124m'[39m[38;5;124m実質利子率[39m[38;5;124m'[39m, data[38;5;241m=[39mdf_res_2, linewidth[38;5;241m=[39m[38;5;241m4[39m, linestyle[38;5;241m=[39m[38;5;124m'[39m[38;5;124m:[39m[38;5;124m'[39m)
[1;32m     19[0m ax[[38;5;241m1[39m,[38;5;241m1[39m][38;5;241m.[39mset_title([38;5;124m'[39m[38;5;124m実質利子率[39m[38;5;124m'[39m,size[38;5;241m=[39m[38;5;241m20[39m)
[0;32m---> 21[0m [43mfig[49m[38;5;241m.[39mlegend([[38;5;124m'[39m[38;5;124mケース１[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mケース２[39m[38;5;124m'[39m],             [38;5;66;03m#8[39;00m
[1;32m     22[0m            fontsize[38;5;241m=[39m[38;5;241m13[39m,                      [38;5;66;03m#9[39;00m
[1;32m     23[0m            ncol[38;5;241m=[39m[38;5;241m2[39m,                           [38;5;66;03m#10[39;00m
[1;32m     24[0m            loc[38;5;241m=[39m[38;5;241m7[39m)
[1;32m     25[0m [38;5;66;03m#            bbox_to_anchor=(0.7, 1.1))        # 11[39;00m
[1;32m     26[0m [38;5;28;01mpass[39;00m

[0;31mNameError[0m: name 'fig' is not defined

