Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# SUR -> the same result
from linearmodels.system import SUR
df['total_hours_cycle_lag'] = df['total_hours_cycle'].shift()
eq1 = 'tfp_cycle ~ tfp_cycle_lag + total_hours_cycle_lag'
eq2 = 'total_hours_cycle ~  tfp_cycle_lag + total_hours_cycle_lag'
# Create the SUR model
model = SUR.from_formula({'eq1': eq1, 'eq2': eq2}, data=df.dropna(subset=['tfp_cycle_lag', 'total_hours_cycle_lag']))
results = model.fit()
print(results.resids.cov())
print(results.summary.tables[1])
print(results.summary.tables[2])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[48], line 2[0m
[1;32m      1[0m [38;5;66;03m# SUR -> the same result[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mlinearmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01msystem[39;00m [38;5;28;01mimport[39;00m SUR
[1;32m      3[0m df[[38;5;124m'[39m[38;5;124mtotal_hours_cycle_lag[39m[38;5;124m'[39m] [38;5;241m=[39m df[[38;5;124m'[39m[38;5;124mtotal_hours_cycle[39m[38;5;124m'[39m][38;5;241m.[39mshift()
[1;32m      4[0m eq1 [38;5;241m=[39m [38;5;124m'[39m[38;5;124mtfp_cycle ~ tfp_cycle_lag + total_hours_cycle_lag[39m[38;5;124m'[39m

[0;31mModuleNotFoundError[0m: No module named 'linearmodels'

